name: budget_bud
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.7.1
  firebase_auth: ^4.3.0
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.5.2
  flutter_svg: ^2.0.5
  flutter_custom_clippers: ^2.1.0

  showcaseview:

  flutter_snake_navigationbar: ^0.6.1

  google_fonts: ^4.0.3
  provider: ^6.0.5 #can be removed
  shared_preferences: ^2.0.5
  connectivity_plus: ^3.0.4
  awesome_snackbar_content: ^0.1.3
  responsive_sizer: ^3.1.1
  #asdfasdf///
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  #VALIDATORS
  validators: ^3.0.0
  flutter_slidable: ^3.0.0
  fl_chart: ^0.62.0

  #ML KITS
  google_mlkit_text_recognition: ^0.6.0
  camera: ^0.10.5+2
  permission_handler: ^10.2.0
  image_picker: ^0.8.7+5
  flutter_heatmap_calendar: ^1.0.5
  flutter_markdown: ^0.6.15




#testing
  honey: any

  #updater:
  upgrader: ^7.0.2
  http: ^0.13.6
  flutter_html: ^3.0.0-beta.2
  liquid_pull_to_refresh: ^3.0.1
  awesome_notifications: ^0.6.19
  loading_animation_widget: ^1.2.0+4
  flutter_toggle_tab: ^1.3.0
  page_view_dot_indicator: ^2.1.0
  loop_page_view: ^1.2.2






dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19




############################FOR SPLASH SCREEN######################
flutter_native_splash:
  image: assets/bbLogo.png
  color: "#4E3EC8"
###CLI: flutter pub run flutter_native_splash:create
###############################END#################################


flutter:


  uses-material-design: true

  assets:
    - assets/
    - images/
    - assets/other/
    - assets/pointer/
    - assets/category/
    - images/onboarding_page/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
