// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsUxJ4HyRDKhCqNougQUDozlc6_EZnoGM',
    appId: '1:718638126645:web:d8db5484b8f3e9a544c37c',
    messagingSenderId: '718638126645',
    projectId: 'budgetbud-19654',
    authDomain: 'budgetbud-19654.firebaseapp.com',
    storageBucket: 'budgetbud-19654.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgpk2Y0Gk0ZlPDSu01WG0leyWD4sYjDg',
    appId: '1:718638126645:android:68a25fa14298f3b844c37c',
    messagingSenderId: '718638126645',
    projectId: 'budgetbud-19654',
    storageBucket: 'budgetbud-19654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClTaAp0pbtZtc48WR-4O07SBGfSFzlu84',
    appId: '1:718638126645:ios:8ab314602d889eba44c37c',
    messagingSenderId: '718638126645',
    projectId: 'budgetbud-19654',
    storageBucket: 'budgetbud-19654.appspot.com',
    androidClientId: '718638126645-1h865rldnfaj6atam9rsegtfs5vgncsn.apps.googleusercontent.com',
    iosClientId: '718638126645-hcmb4dq61qhqdm0su72bf51fot7ogd2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetBud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClTaAp0pbtZtc48WR-4O07SBGfSFzlu84',
    appId: '1:718638126645:ios:8ab314602d889eba44c37c',
    messagingSenderId: '718638126645',
    projectId: 'budgetbud-19654',
    storageBucket: 'budgetbud-19654.appspot.com',
    androidClientId: '718638126645-1h865rldnfaj6atam9rsegtfs5vgncsn.apps.googleusercontent.com',
    iosClientId: '718638126645-hcmb4dq61qhqdm0su72bf51fot7ogd2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetBud',
  );
}
