final List<String> incomeCategories = [
  'Employment Income',
  'Self-Employment Income',
  'Rental Income',
  'Investment Income',
  'Retirement Income',
  'Social Security Income',
  'Royalties',
  'Commission Income',
  'Bonus Income',
  'Alimony/Child Support',
  'Lottery/Gambling Winnings',
  'Capital Gains',
  'Rental Property Income',
  'Dividend Income',
  'Annuity Payments',
];

final List<String> expenseCategories = [
  'Housing Expenses',
  'Utilities',
  'Transportation Expenses',
  'Food and Groceries',
  'Health and Medical Expenses',
  'Debt Payments',
  'Personal Care',
  'Education Expenses',
  'Entertainment',
  'Clothing and Accessories',
  'Insurance Premiums',
  'Savings and Investments',
  'Charitable Donations',
  'Travel Expenses',
  'Home Maintenance',
];
